1.【填空】如下代码的运行结果为：（ ）。
```
import numpy as np  
np.arange(1,20,4) ```

答案：array([ 1,  5,  9, 13, 17])。

2.【填空】如下代码的运行结果为：（）。
```
import numpy as np  
myArray2=np.arange(1,22).reshape([3,7])
myArray2[[0,2],3]```

答案：array([ 4, 18])。

3.【填空】如下代码的运行结果为：（）。
```
import numpy as np
myArray1=np.array(range(5,15))
myArray2=myArray1.copy()
myArray2[1]=1
myArray3=myArray2
myArray3[2]=2
print(myArray1)
print(myArray2)
print(myArray3)```

答案：  
[ 5  6  7  8  9 10 11 12 13 14]   
[ 5  1  2  8  9 10 11 12 13 14]   
[ 5  1  2  8  9 10 11 12 13 14]

4.【填空】如下代码的运行结果为：（ ）。  
```
import numpy as np  
myArray1=np.arange(1,11).reshape([2,5])
myArray2=np.arange(-11,-1).reshape([2,5])
np.add(myArray1,myArray2)```

答案：  
```array([[-10,  -8,  -6,  -4,  -2],
       [  0,   2,   4,   6,   8]])```

5.【填空】如下代码的运行结果为：（ ）。  
```
import numpy as np  
myArray1=np.arange(1,11).reshape([2,5])
myArray2=np.delete(myArray1,0,0)
np.delete(myArray2,1,1)```

答案：array([[ 6,  8,  9, 10]])。

6.【判断】在查看数组形状或进行重构时，方法reshape()、swapaxes(0,1)不会改变数组本身，而resize()、astype()更改数组本身。（ ）  

A. √  
B. ×

答案：B。

7.【判断】array1+array2时，若两者行数或列数不一样，则解释器将报ValueError错误。（ ）  

A. √  
B. ×

答案：B。

8.【判断】执行如下程序后，将产生如下输出结果。（ ）
```
import numpy as np  
MyArray=np.array([[3,6,9,12],
                  [2,5,8,11],
                  [1,4,7,10]])
np.sort(MyArray,axis=0)
MyArray```
程序运行结果：

```
array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])```
A. √  
B. ×

答案：B。  
解析：MyArray本身并未被改变。