# 35.随机数

## 35.1 一次生成一个数

In [1]:
import random
random.seed(3)

In [2]:
import random
random.seed(3) 
random.randint(1, 100)

31

In [3]:
import random
random.seed(3)
random.uniform(-10, 10)

-5.240707458162173

In [4]:
random.uniform?

In [5]:
random.seed(3)
round(random.uniform(-10, 10),2) 

-5.24

## 35.2 一次生成一个随机数组

In [7]:
import numpy as np
rand=np.random.RandomState(32)

x=rand.randint(0,10,(3,6))
x

array([[7, 5, 6, 8, 3, 7],
       [9, 3, 5, 9, 4, 1],
       [3, 1, 2, 3, 8, 2]])

In [8]:
import numpy as np
rand=np.random.RandomState(1)
x=rand.rand(5) *10 

x

array([4.17022005e+00, 7.20324493e+00, 1.14374817e-03, 3.02332573e+00,
       1.46755891e+00])

In [9]:
import numpy as np
rand=np.random.RandomState(1)
y=  rand.randn(5) +5

y

array([6.62434536, 4.38824359, 4.47182825, 3.92703138, 5.86540763])

In [10]:
x=np.linspace(0,10,20) 

x

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [11]:
np.linspace?