# 36.数组

In [2]:
import numpy as np  

## 36.1 创建方法

In [4]:
MyArray1 = np.arange(1,20) 
MyArray1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [5]:
range(1,10,2)

range(1, 10, 2)

In [6]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
MyArray2=np.array([1,2,3,4,3,5])
MyArray2

array([1, 2, 3, 4, 3, 5])

In [9]:
np.array(range(1,10,2))

array([1, 3, 5, 7, 9])

In [10]:
MyArray3=np.zeros((5,5)) 
MyArray3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
MyArray4=np.ones((5,5))
MyArray4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full((3,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [13]:
rand=np.random.RandomState(30)

MyArray5=rand.randint(0,100,[3,5])
MyArray5

array([[37, 37, 45, 45, 12],
       [23,  2, 53, 17, 46],
       [ 3, 41,  7, 65, 49]])

## 36.2 主要特征

In [15]:
import numpy as np  
MyArray4=np.zeros(shape=(2,15),dtype=np.int)
MyArray4

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.ones([3,5],dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 36.3 切片/读取

In [19]:
import numpy as np  
myArray=np.array(range(1,10)) 
      
myArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
myArray=np.arange(1,10)
myArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
myArray[0]

1

In [22]:
myArray[-1]

9

In [23]:
import numpy as np
myArray=np.array(range(0,10))

print("myArray=",myArray)
print("myArray[1:9:2]=",myArray[1:9:2]) 
print("myArray[:9:2]=",myArray[:9:2]) 
print("myArray[::2]=",myArray[::2]) 
print("myArray[::]=",myArray[::])   
print("myArray[:8:]=",myArray[:8:])  
print("myArray[:8]=",myArray[0:8])  
print("myArray[4::]=",myArray[4::])  
print("myArray[9:1:-2]=",myArray[9:1:-2]) 
print("myArray[::-2]=",myArray[::-2])   
print("myArray[[2,5,6]]=",myArray[[2,5,6]]) 
print("myArray[myArray>5]=",myArray[myArray>5]) 

myArray= [0 1 2 3 4 5 6 7 8 9]
myArray[1:9:2]= [1 3 5 7]
myArray[:9:2]= [0 2 4 6 8]
myArray[::2]= [0 2 4 6 8]
myArray[::]= [0 1 2 3 4 5 6 7 8 9]
myArray[:8:]= [0 1 2 3 4 5 6 7]
myArray[:8]= [0 1 2 3 4 5 6 7]
myArray[4::]= [4 5 6 7 8 9]
myArray[9:1:-2]= [9 7 5 3]
myArray[::-2]= [9 7 5 3 1]
myArray[[2,5,6]]= [2 5 6]
myArray[myArray>5]= [6 7 8 9]


In [24]:
myArray[0:2]

array([0, 1])

In [25]:
myArray[1:5:2]

array([1, 3])

In [26]:
myArray[::2] 

array([0, 2, 4, 6, 8])

In [27]:
myArray[::-2] 

array([9, 7, 5, 3, 1])

In [28]:
myArray  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
myArray=np.array(range(1,11))
myArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
myArray[1,3,6]

IndexError: too many indices for array

In [31]:
myArray[[1,3,6]]

array([2, 4, 7])

In [32]:
myArray 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
myArray[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [34]:
myArray[:,np.newaxis].shape

(10, 1)

In [35]:
myArray2=np.arange(1,21).reshape([5,4])
myArray2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [36]:
myArray2[[2,4],3]

array([12, 20])

In [37]:
x=[2,4]
myArray2[x,3]

array([12, 20])

## 36.4 浅拷贝与深拷贝

In [38]:
import numpy as np
myArray1=np.array(range(0,10))
myArray2=myArray1
myArray2[1]=100 
myArray1

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [39]:
import numpy as np
myArray1=np.array(range(0,10))
myArray2=myArray1.copy()
myArray2[1]=200 
myArray1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 36.5 形状与重构

In [40]:
import numpy as np  
MyArray5=np.arange(1,21)  
MyArray5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
MyArray5.shape

(20,)

In [42]:
MyArray6=MyArray5.reshape(4,5)  
MyArray6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
MyArray5.shape

(20,)

In [44]:
MyArray5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
MyArray5.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [46]:
MyArray5.reshape(5,5) 

ValueError: cannot reshape array of size 20 into shape (5,5)

In [47]:
MyArray5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
MyArray5.resize(4,5)
MyArray5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [49]:
MyArray5.swapaxes(0,1)

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [50]:
MyArray5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [51]:
MyArray5=MyArray5.swapaxes(0,1)
MyArray5

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [52]:
MyArray5.flatten()

array([ 1,  6, 11, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,  9, 14, 19,  5,
       10, 15, 20])

In [53]:
MyArray5.tolist()

[[1, 6, 11, 16],
 [2, 7, 12, 17],
 [3, 8, 13, 18],
 [4, 9, 14, 19],
 [5, 10, 15, 20]]

In [54]:
MyArray5.astype(np.float)

array([[ 1.,  6., 11., 16.],
       [ 2.,  7., 12., 17.],
       [ 3.,  8., 13., 18.],
       [ 4.,  9., 14., 19.],
       [ 5., 10., 15., 20.]])

In [55]:
MyArray5 

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

## 36.6 属性计算

In [56]:
np.rank(MyArray5)  

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  This is separate from the ipykernel package so we can avoid doing imports until


2

In [57]:
np.ndim(MyArray5)

2

In [58]:
MyArray5.ndim

2

In [59]:
np.shape(MyArray5)

(5, 4)

In [60]:
MyArray5.shape    

(5, 4)

In [61]:
MyArray5.size

20

In [62]:
type(MyArray5)  

numpy.ndarray

## 36.7 ndarray的计算

In [63]:
MyArray5*10

array([[ 10,  60, 110, 160],
       [ 20,  70, 120, 170],
       [ 30,  80, 130, 180],
       [ 40,  90, 140, 190],
       [ 50, 100, 150, 200]])

In [64]:
x=np.array([11,12,13,14,15,16,17,18])
x1,x2,x3=np.split(x,[3,5]) 
print(x1,x2,x3)

[11 12 13] [14 15] [16 17 18]


In [65]:
upper,lower=np.vsplit(MyArray5.reshape(4,5),[2])
print("上半部分为\n",upper)
print("\n\n下半部分为\n",lower)

上半部分为
 [[ 1  6 11 16  2]
 [ 7 12 17  3  8]]


下半部分为
 [[13 18  4  9 14]
 [19  5 10 15 20]]


In [66]:
np.concatenate((lower,upper),axis=0)

array([[13, 18,  4,  9, 14],
       [19,  5, 10, 15, 20],
       [ 1,  6, 11, 16,  2],
       [ 7, 12, 17,  3,  8]])

In [67]:
np.vstack([upper,lower])

array([[ 1,  6, 11, 16,  2],
       [ 7, 12, 17,  3,  8],
       [13, 18,  4,  9, 14],
       [19,  5, 10, 15, 20]])

In [68]:
np.hstack([upper,lower])

array([[ 1,  6, 11, 16,  2, 13, 18,  4,  9, 14],
       [ 7, 12, 17,  3,  8, 19,  5, 10, 15, 20]])

In [69]:
np.add(MyArray5,1)   

array([[ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20],
       [ 6, 11, 16, 21]])

## 36.8 ndarray的元素类型

In [70]:
import numpy as np  
np.zeros(10,dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [71]:
np.zeros(10,dtype="float")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
a1=np.array([1,2,3,None])
a1

array([1, 2, 3, None], dtype=object)

In [73]:
a1=np.array([1,2,3,None,np.nan])
a1

array([1, 2, 3, None, nan], dtype=object)

## 36.9 插入与删除

In [74]:
import numpy as np
myArray1=np.array([11,12,13,14,15,16,17,18])
np.delete(myArray1,2)

array([11, 12, 14, 15, 16, 17, 18])

In [75]:
np.insert(myArray1,1,88)

array([11, 88, 12, 13, 14, 15, 16, 17, 18])

## 36.10 缺失值处理

In [76]:
np.isnan(myArray)

array([False, False, False, False, False, False, False, False, False,
       False])

In [77]:
np.any(np.isnan(myArray))

False

In [78]:
np.all(np.isnan(myArray))

False

In [79]:
MyArray=np.array([1,2,3,np.nan])
np.nansum(MyArray)

6.0

In [80]:
np.sum(MyArray)

nan

## 36.11 ndarray的广播规则

In [81]:
import numpy as np  
A1=np.array(range(1,10)).reshape([3,3])
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
A2=np.array([10,10,10])
A2

array([10, 10, 10])

In [83]:
A1+A2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [84]:
A3=np.arange(10).reshape(2,5)    
A3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [85]:
A4=np.arange(16).reshape(4,4)
A4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
A3+A4

ValueError: operands could not be broadcast together with shapes (2,5) (4,4) 

## 36.12 ndarray的排序

In [87]:
import numpy as np  
myArray=np.array([11,18,13,12,19,15,14,17,16])
myArray

array([11, 18, 13, 12, 19, 15, 14, 17, 16])

In [88]:
np.sort(myArray)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [89]:
np.argsort(myArray)

array([0, 3, 2, 6, 5, 8, 7, 1, 4], dtype=int64)

In [90]:
MyArray=np.array([[21, 22, 23, 24,25],
       [35,  34,33, 32, 31],
       [ 1, 2,  3, 100, 4]])

In [91]:
np.sort(MyArray,axis=1)

array([[ 21,  22,  23,  24,  25],
       [ 31,  32,  33,  34,  35],
       [  1,   2,   3,   4, 100]])

In [92]:
np.sort(MyArray,axis=0)

array([[  1,   2,   3,  24,   4],
       [ 21,  22,  23,  32,  25],
       [ 35,  34,  33, 100,  31]])